package com.example.covinfo.enums;

public enum TaskType {
    DEVELOPER_LIST,
    ABOUT_APP,
    WORLD_NEWS,
    GLOBAL_DATA,
    REGION_INFO_LIST,
    REGION_DATA_LIST,
    REGION_DATA,
    REGION_COUNTRY_DATA_LIST,
    COUNTRY_DATA_LIST,
    COUNTRY_DATA,
    COUNTRY_DATA_TIME_SERIES,
    INDIA_NEWS,
    INDIA_DATA,
    INDIA_DATA_TIME_SERIES,
    STATE_DATA_LIST,
    STATE_DATA,
    STATE_DATA_TIME_SERIES,
    DISTRICT_DATA_LIST,
    DISTRICT_DATA,
    DISTRICT_DATA_TIME_SERIES
}
